#include <stddef.h>

#include "api.h"
#include "inner.h"

color_t colors_48gx[ NB_COLORS ] = {
    /* UI4X_COLOR_HP_LOGO */
    {
     .a = 0xFF,
     .mono_rgb = 0xFF,
     .gray_rgb = 0xB0,
     .rgb = 0xB0B0B8,
     },
    /* UI4X_COLOR_HP_LOGO_BG */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x68,
     .rgb = 0x68686E,
     },
    /* UI4X_COLOR_48GX_128K_RAM */
    {
     .a = 0xFF,
     .mono_rgb = 0xFF,
     .gray_rgb = 0xF0,
     .rgb = 0xF0F0F0,
     },
    /* UI4X_COLOR_FRAME */
    {
     .a = 0xFF,
     .mono_rgb = 0xFF,
     .gray_rgb = 0x0,
     .rgb = 0x000000,
     },
    /* UI4X_COLOR_UPPER_FACEPLATE_EDGE_TOP */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x80,
     .rgb = 0x80808A,
     },
    /* UI4X_COLOR_UPPER_FACEPLATE */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x68,
     .rgb = 0x68686E,
     },
    /* UI4X_COLOR_UPPER_FACEPLATE_EDGE_BOTTOM */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x54,
     .rgb = 0x54545A,
     },
    /* UI4X_COLOR_FACEPLATE_EDGE_TOP */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x58,
     .rgb = 0x585858,
     },
    /* UI4X_COLOR_FACEPLATE */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x4A,
     .rgb = 0x4A4A4A,
     },
    /* UI4X_COLOR_FACEPLATE_EDGE_BOTTOM */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x40,
     .rgb = 0x404040,
     },
    /* UI4X_COLOR_KEYPAD_HIGHLIGHT */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x68,
     .rgb = 0x68686E,
     },
    /* UI4X_COLOR_BUTTON_EDGE_TOP */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x68,
     .rgb = 0x686868,
     },
    /* UI4X_COLOR_BUTTON */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x58,
     .rgb = 0x585858,
     },
    /* UI4X_COLOR_BUTTON_EDGE_BOTTOM */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x4A,
     .rgb = 0x4A4A4A,
     },
    /* UI4X_COLOR_LABEL */
    {
     .a = 0xFF,
     .mono_rgb = 0xFF,
     .gray_rgb = 0xFF,
     .rgb = 0xFFFFFF,
     },
    /* UI4X_COLOR_ALPHA */
    {
     .a = 0xFF,
     .mono_rgb = 0xFF,
     .gray_rgb = 0xFF,
     .rgb = 0xFFFFFF,
     },
    /* UI4X_COLOR_LEFTSHIFT */
    {
     .a = 0xFF,
     .mono_rgb = 0xFF,
     .gray_rgb = 0xDC,
     .rgb = 0xFFBAFF,
     },
    /* UI4X_COLOR_RIGHTSHIFT */
    {
     .a = 0xFF,
     .mono_rgb = 0xFF,
     .gray_rgb = 0xA9,
     .rgb = 0x00FFCC,
     },
    /* UI4X_COLOR_ANNUNCIATOR */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x14,
     .rgb = 0x253d54,
     },
    /* UI4X_COLOR_LCD_BG */
    {
     .a = 0xFF,
     .mono_rgb = 0xFF,
     .gray_rgb = 0xCD,
     .rgb = 0x779988,
     },
    /* UI4X_COLOR_BLACK_LCD_BG */
    {
     .a = 0xFF,
     .mono_rgb = 0xFF,
     .gray_rgb = 0xCD,
     .rgb = 0xf5f5f5,
     },
    /* UI4X_COLOR_PIXEL_ON */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x14,
     .rgb = 0x253d54,
     },
    /* UI4X_COLOR_BLACK_PIXEL_ON */
    {
     .a = 0xFF,
     .mono_rgb = 0x0,
     .gray_rgb = 0x14,
     .rgb = 0x151515,
     },
};

#define KB_LINE_HEIGHT 50
#define KB_COLUMN_WIDTH_6_KEYS 50
#define KB_COLUMN_WIDTH_5_KEYS 60

button_t buttons_48gx[ NB_HP48_KEYS ] = {
    {
     .x = 0,
     .y = 0,
     .w = 36,
     .h = 23,
     .label_color = UI4X_COLOR_LABEL,
     .label = "◽",
     .label_sdl = NULL,
     .label_graphic_w = menu_label_width,
     .label_graphic_h = menu_label_height,
     .label_graphic = menu_label_bitmap,
     .letter = "A",
     .left = NULL,
     .left_sdl = NULL,
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "menu",
     .css_id = "A",
     .hpkey = HP48_KEY_A,
     },

    {
     .x = KB_COLUMN_WIDTH_6_KEYS,
     .y = 0,
     .w = 36,
     .h = 23,
     .label_color = UI4X_COLOR_LABEL,
     .label = "◽",
     .label_sdl = NULL,
     .label_graphic_w = menu_label_width,
     .label_graphic_h = menu_label_height,
     .label_graphic = menu_label_bitmap,
     .letter = "B",
     .left = NULL,
     .left_sdl = NULL,
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "menu",
     .css_id = "B",
     .hpkey = HP48_KEY_B,
     },

    {
     .x = 2 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 0,
     .w = 36,
     .h = 23,
     .label_color = UI4X_COLOR_LABEL,
     .label = "◽",
     .label_sdl = NULL,
     .label_graphic_w = menu_label_width,
     .label_graphic_h = menu_label_height,
     .label_graphic = menu_label_bitmap,
     .letter = "C",
     .left = NULL,
     .left_sdl = NULL,
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "menu",
     .css_id = "C",
     .hpkey = HP48_KEY_C,
     },

    {
     .x = 3 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 0,
     .w = 36,
     .h = 23,
     .label_color = UI4X_COLOR_LABEL,
     .label = "◽",
     .label_sdl = NULL,
     .label_graphic_w = menu_label_width,
     .label_graphic_h = menu_label_height,
     .label_graphic = menu_label_bitmap,
     .letter = "D",
     .left = NULL,
     .left_sdl = NULL,
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "menu",
     .css_id = "D",
     .hpkey = HP48_KEY_D,
     },

    {
     .x = 4 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 0,
     .w = 36,
     .h = 23,
     .label_color = UI4X_COLOR_LABEL,
     .label = "◽",
     .label_sdl = NULL,
     .label_graphic_w = menu_label_width,
     .label_graphic_h = menu_label_height,
     .label_graphic = menu_label_bitmap,
     .letter = "E",
     .left = NULL,
     .left_sdl = NULL,
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "menu",
     .css_id = "E",
     .hpkey = HP48_KEY_E,
     },

    {
     .x = 5 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 0,
     .w = 36,
     .h = 23,
     .label_color = UI4X_COLOR_LABEL,
     .label = "◽",
     .label_sdl = NULL,
     .label_graphic_w = menu_label_width,
     .label_graphic_h = menu_label_height,
     .label_graphic = menu_label_bitmap,
     .letter = "F",
     .left = NULL,
     .left_sdl = NULL,
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "menu",
     .css_id = "F",
     .hpkey = HP48_KEY_F,
     },

    {
     .x = 0,
     .y = KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "MTH",
     .label_sdl = "MTH",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = "G",
     .left = "RAD",
     .left_sdl = "RAD",
     .highlight = false,
     .right = "POLAR",
     .right_sdl = "POLAR",
     .below = NULL,
     .css_class = "function",
     .css_id = "G",
     .hpkey = HP48_KEY_G,
     },

    {
     .x = KB_COLUMN_WIDTH_6_KEYS,
     .y = KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "PRG",
     .label_sdl = "PRG",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = "H",
     .left = "CHARS",
     .left_sdl = "CHARS",
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "function",
     .css_id = "H",
     .hpkey = HP48_KEY_H,
     },

    {
     .x = 2 * KB_COLUMN_WIDTH_6_KEYS,
     .y = KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "CST",
     .label_sdl = "CST",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = "I",
     .left = "MODES",
     .left_sdl = "MODES",
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "function",
     .css_id = "I",
     .hpkey = HP48_KEY_I,
     },

    {
     .x = 3 * KB_COLUMN_WIDTH_6_KEYS,
     .y = KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "VAR",
     .label_sdl = "VAR",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = "J",
     .left = "MEMORY",
     .left_sdl = "MEMORY",
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "function",
     .css_id = "J",
     .hpkey = HP48_KEY_J,
     },

    {
     .x = 4 * KB_COLUMN_WIDTH_6_KEYS,
     .y = KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "▲",
     .label_sdl = NULL,
     .label_graphic_w = up_width,
     .label_graphic_h = up_height,
     .label_graphic = up_bitmap,
     .letter = "K",
     .left = "STACK",
     .left_sdl = "STACK",
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "function arrow",
     .css_id = "K",
     .hpkey = HP48_KEY_K,
     },

    {
     .x = 5 * KB_COLUMN_WIDTH_6_KEYS,
     .y = KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "NXT",
     .label_sdl = "NXT",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = "L",
     .left = "PREV",
     .left_sdl = "PREV",
     .highlight = false,
     .right = "MENU",
     .right_sdl = "MENU",
     .below = NULL,
     .css_class = "function",
     .css_id = "L",
     .hpkey = HP48_KEY_L,
     },

    {
     .x = 0,
     .y = 2 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "'",
     .label_sdl = NULL,
     .label_graphic_w = quote_width,
     .label_graphic_h = quote_height,
     .label_graphic = quote_bitmap,
     .letter = "M",
     .left = "UP",
     .left_sdl = "UP",
     .highlight = false,
     .right = "HOME",
     .right_sdl = "HOME",
     .below = NULL,
     .css_class = "function",
     .css_id = "M",
     .hpkey = HP48_KEY_M,
     },

    {
     .x = KB_COLUMN_WIDTH_6_KEYS,
     .y = 2 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "STO",
     .label_sdl = "STO",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = "N",
     .left = "DEF",
     .left_sdl = "DEF",
     .highlight = false,
     .right = "RCL",
     .right_sdl = "RCL",
     .below = NULL,
     .css_class = "function",
     .css_id = "N",
     .hpkey = HP48_KEY_N,
     },

    {
     .x = 2 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 2 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "EVAL",
     .label_sdl = "EVAL",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = "O",
     .left = "→NUM",
     .left_sdl = "\x06NUM",
     .highlight = false,
     .right = "UNDO",
     .right_sdl = "UNDO",
     .below = NULL,
     .css_class = "function",
     .css_id = "O",
     .hpkey = HP48_KEY_O,
     },

    {
     .x = 3 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 2 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "◀",
     .label_sdl = NULL,
     .label_graphic_w = left_width,
     .label_graphic_h = left_height,
     .label_graphic = left_bitmap,
     .letter = "P",
     .left = "PICTURE",
     .left_sdl = "PICTURE",
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "function arrow",
     .css_id = "P",
     .hpkey = HP48_KEY_P,
     },

    {
     .x = 4 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 2 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "▼",
     .label_sdl = NULL,
     .label_graphic_w = down_width,
     .label_graphic_h = down_height,
     .label_graphic = down_bitmap,
     .letter = "Q",
     .left = "VIEW",
     .left_sdl = "VIEW",
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "function arrow",
     .css_id = "Q",
     .hpkey = HP48_KEY_Q,
     },

    {
     .x = 5 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 2 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "▶",
     .label_sdl = NULL,
     .label_graphic_w = right_width,
     .label_graphic_h = right_height,
     .label_graphic = right_bitmap,
     .letter = "R",
     .left = "SWAP",
     .left_sdl = "SWAP",
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "function arrow",
     .css_id = "R",
     .hpkey = HP48_KEY_R,
     },

    {
     .x = 0,
     .y = 3 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "SIN",
     .label_sdl = "SIN",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = "S",
     .left = "ASIN",
     .left_sdl = "ASIN",
     .highlight = false,
     .right = "𝛅",
     .right_sdl = "\x07",
     .below = NULL,
     .css_class = "function",
     .css_id = "S",
     .hpkey = HP48_KEY_S,
     },

    {
     .x = KB_COLUMN_WIDTH_6_KEYS,
     .y = 3 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "COS",
     .label_sdl = "COS",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = "T",
     .left = "ACOS",
     .left_sdl = "ACOS",
     .highlight = false,
     .right = "∫",
     .right_sdl = "\x08",
     .below = NULL,
     .css_class = "function",
     .css_id = "T",
     .hpkey = HP48_KEY_T,
     },

    {
     .x = 2 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 3 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "TAN",
     .label_sdl = "TAN",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = "U",
     .left = "ATAN",
     .left_sdl = "ATAN",
     .highlight = false,
     .right = "∑",
     .right_sdl = "\x09",
     .below = NULL,
     .css_class = "function",
     .css_id = "U",
     .hpkey = HP48_KEY_U,
     },

    {
     .x = 3 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 3 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "√𝓍",
     .label_sdl = NULL,
     .label_graphic_w = sqrt_width,
     .label_graphic_h = sqrt_height,
     .label_graphic = sqrt_bitmap,
     .letter = "V",
     .left = "𝓍²",
     .left_sdl = "\x13",
     .highlight = false,
     .right = "𝓍√𝓎",
     .right_sdl = "\x14",
     .below = NULL,
     .css_class = "function",
     .css_id = "V",
     .hpkey = HP48_KEY_V,
     },

    {
     .x = 4 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 3 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "𝓎^𝓍",
     .label_sdl = NULL,
     .label_graphic_w = power_width,
     .label_graphic_h = power_height,
     .label_graphic = power_bitmap,
     .letter = "W",
     .left = "10^𝓍",
     .left_sdl = "\x15",
     .highlight = false,
     .right = "LOG",
     .right_sdl = "LOG",
     .below = NULL,
     .css_class = "function",
     .css_id = "W",
     .hpkey = HP48_KEY_W,
     },

    {
     .x = 5 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 3 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "1/𝓍",
     .label_sdl = NULL,
     .label_graphic_w = inv_width,
     .label_graphic_h = inv_height,
     .label_graphic = inv_bitmap,
     .letter = "X",
     .left = "e^𝓍",
     .left_sdl = "\x16",
     .highlight = false,
     .right = "LN",
     .right_sdl = "LN",
     .below = NULL,
     .css_class = "function",
     .css_id = "X",
     .hpkey = HP48_KEY_X,
     },

    {
     .x = 0,
     .y = 4 * KB_LINE_HEIGHT,
     .w = 86,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "ENTER",
     .label_sdl = "ENTER",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = "EQUATION",
     .left_sdl = "EQUATION",
     .highlight = false,
     .right = "MATRIX",
     .right_sdl = "MATRIX",
     .below = NULL,
     .css_class = "enter",
     .css_id = "ENTER",
     .hpkey = HP48_KEY_ENTER,
     },

    {
     .x = 2 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 4 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "+/-",
     .label_sdl = NULL,
     .label_graphic_w = neg_width,
     .label_graphic_h = neg_height,
     .label_graphic = neg_bitmap,
     .letter = "Y",
     .left = "EDIT",
     .left_sdl = "EDIT",
     .highlight = false,
     .right = "CMD",
     .right_sdl = "CMD",
     .below = NULL,
     .css_class = "function",
     .css_id = "Y",
     .hpkey = HP48_KEY_Y,
     },

    {
     .x = 3 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 4 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "EEX",
     .label_sdl = "EEX",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = "Z",
     .left = "PURG",
     .left_sdl = "PURG",
     .highlight = false,
     .right = "ARG",
     .right_sdl = "ARG",
     .below = NULL,
     .css_class = "function",
     .css_id = "Z",
     .hpkey = HP48_KEY_Z,
     },

    {
     .x = 4 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 4 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "DEL",
     .label_sdl = "DEL",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = "CLEAR",
     .left_sdl = "CLEAR",
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "function",
     .css_id = "DEL",
     .hpkey = HP48_KEY_DEL,
     },

    {
     .x = 5 * KB_COLUMN_WIDTH_6_KEYS,
     .y = 4 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "⬅",
     .label_sdl = NULL,
     .label_graphic_w = bs_width,
     .label_graphic_h = bs_height,
     .label_graphic = bs_bitmap,
     .letter = NULL,
     .left = "DROP",
     .left_sdl = "DROP",
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "function",
     .css_id = "BACKSPACE",
     .hpkey = HP48_KEY_BACKSPACE,
     },

    {
     .x = 0,
     .y = 5 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "𝝰",
     .label_sdl = NULL,
     .label_graphic_w = alpha_width,
     .label_graphic_h = alpha_height,
     .label_graphic = alpha_bitmap,
     .letter = NULL,
     .left = "USER",
     .left_sdl = "USER",
     .highlight = false,
     .right = "ENTRY",
     .right_sdl = "ENTRY",
     .below = NULL,
     .css_class = "core alpha",
     .css_id = "ALPHA",
     .hpkey = HP48_KEY_ALPHA,
     },

    {
     .x = KB_COLUMN_WIDTH_5_KEYS,
     .y = 5 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "7",
     .label_sdl = "7",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = NULL,
     .left_sdl = NULL,
     .highlight = true,
     .right = "SOLVE",
     .right_sdl = "SOLVE",
     .below = NULL,
     .css_class = "core-number",
     .css_id = "SEVEN",
     .hpkey = HP48_KEY_7,
     },

    {
     .x = 2 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 5 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "8",
     .label_sdl = "8",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = NULL,
     .left_sdl = NULL,
     .highlight = true,
     .right = "PLOT",
     .right_sdl = "PLOT",
     .below = NULL,
     .css_class = "core-number",
     .css_id = "EIGHT",
     .hpkey = HP48_KEY_8,
     },

    {
     .x = 3 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 5 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "9",
     .label_sdl = "9",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = NULL,
     .left_sdl = NULL,
     .highlight = true,
     .right = "SYMBOLIC",
     .right_sdl = "SYMBOLIC",
     .below = NULL,
     .css_class = "core-number",
     .css_id = "NINE",
     .hpkey = HP48_KEY_9,
     },

    {
     .x = 4 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 5 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "÷",
     .label_sdl = NULL,
     .label_graphic_w = div_width,
     .label_graphic_h = div_height,
     .label_graphic = div_bitmap,
     .letter = NULL,
     .left = "()",
     .left_sdl = "\x17 ",
     .highlight = false,
     .right = "#",
     .right_sdl = "\x18",
     .below = NULL,
     .css_class = "core",
     .css_id = "DIVIDE",
     .hpkey = HP48_KEY_DIVIDE,
     },

    {
     .x = 0,
     .y = 6 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LEFTSHIFT,
     .label = "⮪",
     .label_sdl = NULL,
     .label_graphic_w = shl_width,
     .label_graphic_h = shl_height,
     .label_graphic = shl_bitmap,
     .letter = NULL,
     .left = NULL,
     .left_sdl = NULL,
     .highlight = false,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "shift-left",
     .css_id = "SHIFTLEFT",
     .hpkey = HP48_KEY_LEFTSHIFT,
     },

    {
     .x = KB_COLUMN_WIDTH_5_KEYS,
     .y = 6 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "4",
     .label_sdl = "4",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = NULL,
     .left_sdl = NULL,
     .highlight = true,
     .right = "TIME",
     .right_sdl = "TIME",
     .below = NULL,
     .css_class = "core-number",
     .css_id = "FOUR",
     .hpkey = HP48_KEY_4,
     },

    {
     .x = 2 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 6 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "5",
     .label_sdl = "5",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = NULL,
     .left_sdl = NULL,
     .highlight = true,
     .right = "STAT",
     .right_sdl = "STAT",
     .below = NULL,
     .css_class = "core-number",
     .css_id = "FIVE",
     .hpkey = HP48_KEY_5,
     },

    {
     .x = 3 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 6 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "6",
     .label_sdl = "6",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = NULL,
     .left_sdl = NULL,
     .highlight = true,
     .right = "UNITS",
     .right_sdl = "UNITS",
     .below = NULL,
     .css_class = "core-number",
     .css_id = "SIX",
     .hpkey = HP48_KEY_6,
     },

    {
     .x = 4 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 6 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "×",
     .label_sdl = NULL,
     .label_graphic_w = mul_width,
     .label_graphic_h = mul_height,
     .label_graphic = mul_bitmap,
     .letter = NULL,
     .left = "[]",
     .left_sdl = "\x19 ",
     .highlight = false,
     .right = "_",
     .right_sdl = "\x1a",
     .below = NULL,
     .css_class = "core",
     .css_id = "MULTIPLY",
     .hpkey = HP48_KEY_MUL,
     },

    {
     .x = 0,
     .y = 7 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_RIGHTSHIFT,
     .label = "⮫",
     .label_sdl = NULL,
     .label_graphic_w = shr_width,
     .label_graphic_h = shr_height,
     .label_graphic = shr_bitmap,
     .letter = NULL,
     .left = NULL,
     .left_sdl = NULL,
     .highlight = true,
     .right = NULL,
     .right_sdl = NULL,
     .below = NULL,
     .css_class = "shift-right",
     .css_id = "SHIFTRIGHT",
     .hpkey = HP48_KEY_RIGHTSHIFT,
     },

    {
     .x = KB_COLUMN_WIDTH_5_KEYS,
     .y = 7 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "1",
     .label_sdl = "1",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = NULL,
     .left_sdl = NULL,
     .highlight = true,
     .right = "I/O",
     .right_sdl = "I/O",
     .below = NULL,
     .css_class = "core-number",
     .css_id = "ONE",
     .hpkey = HP48_KEY_1,
     },

    {
     .x = 2 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 7 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "2",
     .label_sdl = "2",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = NULL,
     .left_sdl = NULL,
     .highlight = true,
     .right = "LIBRARY",
     .right_sdl = "LIBRARY",
     .below = NULL,
     .css_class = "core-number",
     .css_id = "TWO",
     .hpkey = HP48_KEY_2,
     },

    {
     .x = 3 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 7 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "3",
     .label_sdl = "3",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = NULL,
     .left_sdl = NULL,
     .highlight = true,
     .right = "EQ LIB",
     .right_sdl = "EQ LIB",
     .below = NULL,
     .css_class = "core-number",
     .css_id = "THREE",
     .hpkey = HP48_KEY_3,
     },

    {
     .x = 4 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 7 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "-",
     .label_sdl = NULL,
     .label_graphic_w = minus_width,
     .label_graphic_h = minus_height,
     .label_graphic = minus_bitmap,
     .letter = NULL,
     .left = "«»",
     .left_sdl = "\x1b ",
     .highlight = false,
     .right = "\"\"",
     .right_sdl = "\x1c",
     .below = NULL,
     .css_class = "core",
     .css_id = "MINUS",
     .hpkey = HP48_KEY_MINUS,
     },

    {
     .x = 0,
     .y = 8 * KB_LINE_HEIGHT,
     .w = 36,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "ON",
     .label_sdl = "ON",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = "CONT",
     .left_sdl = "CONT",
     .highlight = false,
     .right = "OFF",
     .right_sdl = "OFF",
     .below = "CANCEL",
     .css_class = "core",
     .css_id = "ON",
     .hpkey = HP48_KEY_ON,
     },

    {
     .x = KB_COLUMN_WIDTH_5_KEYS,
     .y = 8 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "0",
     .label_sdl = "0",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = "=",
     .left_sdl = "\x04 ",
     .highlight = false,
     .right = "→",
     .right_sdl = "\x03",
     .below = NULL,
     .css_class = "core-number",
     .css_id = "ZERO",
     .hpkey = HP48_KEY_0,
     },

    {
     .x = 2 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 8 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = ".",
     .label_sdl = ".",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = ",",
     .left_sdl = "\x02 ",
     .highlight = false,
     .right = "⮐",
     .right_sdl = "\x01",
     .below = NULL,
     .css_class = "core",
     .css_id = "PERIOD",
     .hpkey = HP48_KEY_PERIOD,
     },

    {
     .x = 3 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 8 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "SPC",
     .label_sdl = "SPC",
     .label_graphic_w = 0,
     .label_graphic_h = 0,
     .label_graphic = NULL,
     .letter = NULL,
     .left = "𝛑",
     .left_sdl = "\x05 ",
     .highlight = false,
     .right = "⦨",
     .right_sdl = "\x1f",
     .below = NULL,
     .css_class = "core",
     .css_id = "SPACE",
     .hpkey = HP48_KEY_SPACE,
     },

    {
     .x = 4 * KB_COLUMN_WIDTH_5_KEYS,
     .y = 8 * KB_LINE_HEIGHT,
     .w = 46,
     .h = 26,
     .label_color = UI4X_COLOR_LABEL,
     .label = "+",
     .label_sdl = NULL,
     .label_graphic_w = plus_width,
     .label_graphic_h = plus_height,
     .label_graphic = plus_bitmap,
     .letter = NULL,
     .left = "{}",
     .left_sdl = "\x1d ",
     .highlight = false,
     .right = "::",
     .right_sdl = "\x1e",
     .below = NULL,
     .css_class = "core",
     .css_id = "PLUS",
     .hpkey = HP48_KEY_PLUS,
     },
};
