#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "config.h"
#include "ui.h"
#include "ui_inner.h"

int last_annunc_state = -1;

unsigned char lcd_nibbles_buffer[ DISP_ROWS ][ NIBS_PER_BUFFER_ROW ];

letter_t small_font[ 128 ] = {
    {0,                 0,                  0                 },
    {nl_gx_width,       nl_gx_height,       nl_gx_bitmap      }, /* \001 == \n gx */
    {comma_gx_width,    comma_gx_height,    comma_gx_bitmap   }, /* \002 == comma gx */
    {arrow_gx_width,    arrow_gx_height,    arrow_gx_bitmap   }, /* \003 == \-> gx */
    {equal_gx_width,    equal_gx_height,    equal_gx_bitmap   }, /* \004 == equal gx */
    {pi_gx_width,       pi_gx_height,       pi_gx_bitmap      }, /* \005 == pi gx */
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 }, /* # 16 */
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {blank_width,       blank_height,       blank_bitmap      }, /* # 32 */
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {hash_width,        hash_height,        hash_bitmap       },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {lbrace_width,      lbrace_height,      lbrace_bitmap     },
    {rbrace_width,      rbrace_height,      rbrace_bitmap     },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {comma_width,       comma_height,       comma_bitmap      },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {slash_width,       slash_height,       slash_bitmap      },
    {0,                 0,                  0                 }, /* # 48 */
    {0,                 0,                  0                 },
    {two_width,         two_height,         two_bitmap        },
    {three_width,       three_height,       three_bitmap      },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {small_colon_width, small_colon_height, small_colon_bitmap},
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {equal_width,       equal_height,       equal_bitmap      },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 }, /* # 64 */
    {A_width,           A_height,           A_bitmap          },
    {B_width,           B_height,           B_bitmap          },
    {C_width,           C_height,           C_bitmap          },
    {D_width,           D_height,           D_bitmap          },
    {E_width,           E_height,           E_bitmap          },
    {F_width,           F_height,           F_bitmap          },
    {G_width,           G_height,           G_bitmap          },
    {H_width,           H_height,           H_bitmap          },
    {I_width,           I_height,           I_bitmap          },
    {J_width,           J_height,           J_bitmap          },
    {K_width,           K_height,           K_bitmap          },
    {L_width,           L_height,           L_bitmap          },
    {M_width,           M_height,           M_bitmap          },
    {N_width,           N_height,           N_bitmap          },
    {O_width,           O_height,           O_bitmap          },
    {P_width,           P_height,           P_bitmap          }, /* # 80 */
    {Q_width,           Q_height,           Q_bitmap          },
    {R_width,           R_height,           R_bitmap          },
    {S_width,           S_height,           S_bitmap          },
    {T_width,           T_height,           T_bitmap          },
    {U_width,           U_height,           U_bitmap          },
    {V_width,           V_height,           V_bitmap          },
    {W_width,           W_height,           W_bitmap          },
    {X_width,           X_height,           X_bitmap          },
    {Y_width,           Y_height,           Y_bitmap          },
    {Z_width,           Z_height,           Z_bitmap          },
    {lbracket_width,    lbracket_height,    lbracket_bitmap   },
    {0,                 0,                  0                 },
    {rbracket_width,    rbracket_height,    rbracket_bitmap   },
    {0,                 0,                  0                 },
    {under_width,       under_height,       under_bitmap      },
    {0,                 0,                  0                 }, /* # 96 */
    {arrow_width,       arrow_height,       arrow_bitmap      }, /* a == left arrow   */
    {diff_width,        diff_height,        diff_bitmap       }, /* b == differential */
    {integral_width,    integral_height,    integral_bitmap   }, /* c == integral */
    {sigma_width,       sigma_height,       sigma_bitmap      }, /* d == sigma */
    {sqr_width,         sqr_height,         sqr_bitmap        }, /* e == sqr */
    {root_width,        root_height,        root_bitmap       }, /* f == root */
    {pow10_width,       pow10_height,       pow10_bitmap      }, /* g == pow10 */
    {exp_width,         exp_height,         exp_bitmap        }, /* h == exp */
    {prog_width,        prog_height,        prog_bitmap       }, /* i == << >> */
    {string_width,      string_height,      string_bitmap     }, /* j == " " */
    {nl_width,          nl_height,          nl_bitmap         }, /* k == New Line */
    {pi_width,          pi_height,          pi_bitmap         }, /* l == pi */
    {angle_width,       angle_height,       angle_bitmap      }, /* m == angle */
    {sqr_gx_width,      sqr_gx_height,      sqr_gx_bitmap     }, /* n == sqr gx */
    {root_gx_width,     root_gx_height,     root_gx_bitmap    }, /* o == root gx */
    {pow10_gx_width,    pow10_gx_height,    pow10_gx_bitmap   }, /* p == pow10 gx */
    {exp_gx_width,      exp_gx_height,      exp_gx_bitmap     }, /* q == exp gx */
    {parens_gx_width,   parens_gx_height,   parens_gx_bitmap  }, /* r == ( ) gx */
    {hash_gx_width,     hash_gx_height,     hash_gx_bitmap    }, /* s == # gx */
    {bracket_gx_width,  bracket_gx_height,  bracket_gx_bitmap }, /* t == [] gx */
    {under_gx_width,    under_gx_height,    under_gx_bitmap   }, /* u == _ gx */
    {prog_gx_width,     prog_gx_height,     prog_gx_bitmap    }, /* v == << >> gx */
    {quote_gx_width,    quote_gx_height,    quote_gx_bitmap   }, /* w == " " gx */
    {curly_gx_width,    curly_gx_height,    curly_gx_bitmap   }, /* x == {} gx */
    {colon_gx_width,    colon_gx_height,    colon_gx_bitmap   }, /* y == :: gx */
    {angle_gx_width,    angle_gx_height,    angle_gx_bitmap   }, /* z == angle gx */
    {lcurly_width,      lcurly_height,      lcurly_bitmap     },
    {0,                 0,                  0                 },
    {rcurly_width,      rcurly_height,      rcurly_bitmap     },
    {0,                 0,                  0                 },
    {0,                 0,                  0                 }
};

color_t colors_sx[ NB_COLORS ] = {
    {
     /* #ffffff */
        .name = "white",
     .r = 255,
     .g = 255,
     .b = 255,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 255,
     },
    {
     /* #ffa600 */
        .name = "left",
     .r = 255,
     .g = 166,
     .b = 0,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 230,
     },
    {
     /* #00d2ff */
        .name = "right",
     .r = 0,
     .g = 210,
     .b = 255,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 169,
     },
    {
     /* #6d5d5d */
        .name = "but_top",
     .r = 109,
     .g = 93,
     .b = 93,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 91,
     },
    {
     /* #5a4d4d */
        .name = "button",
     .r = 90,
     .g = 77,
     .b = 77,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 81,
     },
    {
     /* #4c4141 */
        .name = "but_bot",
     .r = 76,
     .g = 65,
     .b = 65,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 69,
     },
    {
     /* #cadd5c */
        .name = "lcd_col",
     .r = 202,
     .g = 221,
     .b = 92,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 205,
     },
    {
     /* #000080 */
        .name = "pix_col",
     .r = 0,
     .g = 0,
     .b = 128,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 20,
     },
    {
     /* #6d4e4e */
        .name = "pad_top",
     .r = 109,
     .g = 78,
     .b = 78,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 88,
     },
    {
     /* #5a4040 */
        .name = "pad",
     .r = 90,
     .g = 64,
     .b = 64,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 73,
     },
    {
     /* #4c3636 */
        .name = "pad_bot",
     .r = 76,
     .g = 54,
     .b = 54,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 60,
     },
    {
     /* #9b7654 */
        .name = "disp_pad_top",
     .r = 155,
     .g = 118,
     .b = 84,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 124,
     },
    {
     /* #7c5e43 */
        .name = "disp_pad",
     .r = 124,
     .g = 94,
     .b = 67,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 99,
     },
    {
     /* #644b35 */
        .name = "disp_pad_bot",
     .r = 100,
     .g = 75,
     .b = 53,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 79,
     },
    {
     /* #cca96b */
        .name = "logo",
     .r = 204,
     .g = 169,
     .b = 107,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 172,
     },
    {
     /* #404040 */
        .name = "logo_back",
     .r = 64,
     .g = 64,
     .b = 64,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 65,
     },
    {
     /* #cab890 */
        .name = "label",
     .r = 202,
     .g = 184,
     .b = 144,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 185,
     },
    {
     /* #000000 */
        .name = "frame",
     .r = 0,
     .g = 0,
     .b = 0,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 0,
     },
    {
     /* #3c2a2a */
        .name = "underlay",
     .r = 60,
     .g = 42,
     .b = 42,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 48,
     },
    {
     /* #000000 */
        .name = "black",
     .r = 0,
     .g = 0,
     .b = 0,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 0,
     },
};

color_t colors_gx[ NB_COLORS ] = {
    {
     /* #FFFFFF */
        .name = "white",
     .r = 255,
     .g = 255,
     .b = 255,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 255,
     },
    {
     /* #ffbaff */
        .name = "left",
     .r = 255,
     .g = 186,
     .b = 255,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 220,
     },
    {
     /* #00ffcc */
        .name = "right",
     .r = 0,
     .g = 255,
     .b = 204,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 169,
     },
    {
     /* #646464 */
        .name = "but_top",
     .r = 104,
     .g = 104,
     .b = 104,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 104,
     },
    {
     /* #585858 */
        .name = "button",
     .r = 88,
     .g = 88,
     .b = 88,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 88,
     },
    {
     /* #4a4a4a */
        .name = "but_bot",
     .r = 74,
     .g = 74,
     .b = 74,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 74,
     },
    {
     /* #cadd5c */
        .name = "lcd_col",
     .r = 202,
     .g = 221,
     .b = 92,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 205,
     },
    {
     /* #000080 */
        .name = "pix_col",
     .r = 0,
     .g = 0,
     .b = 128,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 20,
     },
    {
     /* #585858 */
        .name = "pad_top",
     .r = 88,
     .g = 88,
     .b = 88,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 88,
     },
    {
     /* #4a4a4a */
        .name = "pad",
     .r = 74,
     .g = 74,
     .b = 74,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 74,
     },
    {
     /* #404040 */
        .name = "pad_bot",
     .r = 64,
     .g = 64,
     .b = 64,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 64,
     },
    {
     /* #808080 */
        .name = "disp_pad_top",
     .r = 128,
     .g = 128,
     .b = 138,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 128,
     },
    {
     /* #68686E */
        .name = "disp_pad",
     .r = 104,
     .g = 104,
     .b = 110,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 104,
     },
    {
     /* #54545a */
        .name = "disp_pad_bot",
     .r = 84,
     .g = 84,
     .b = 90,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 84,
     },
    {
     /* #b0b0b8 */
        .name = "logo",
     .r = 176,
     .g = 176,
     .b = 184,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 176,
     },
    {
     /* #68686e */
        .name = "logo_back",
     .r = 104,
     .g = 104,
     .b = 110,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 104,
     },
    {
     /* #f0f0f0 */
        .name = "label",
     .r = 240,
     .g = 240,
     .b = 240,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 240,
     },
    {
     /* #000000 */
        .name = "frame",
     .r = 0,
     .g = 0,
     .b = 0,
     .a = 255,
     .mono_rgb = 255,
     .gray_rgb = 0,
     },
    {
     /* #68686e */
        .name = "underlay",
     .r = 104,
     .g = 104,
     .b = 110,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 104,
     },
    {
     /* #000000 */
        .name = "black",
     .r = 0,
     .g = 0,
     .b = 0,
     .a = 255,
     .mono_rgb = 0,
     .gray_rgb = 0,
     },
};

button_t buttons_sx[ NB_KEYS ] = {
    {.name = "A",
     .x = 0,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "A",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0     },
    {.name = "B",
     .x = 50,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "B",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0     },
    {.name = "C",
     .x = 100,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "C",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0     },
    {.name = "D",
     .x = 150,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "D",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0     },
    {.name = "E",
     .x = 200,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "E",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0     },
    {.name = "F",
     .x = 250,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "F",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0     },

    {.name = "MTH",
     .x = 0,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "MTH",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "G",
     .left = "PRINT",
     .is_menu = 1,
     .right = 0,
     .sub = 0     },
    {.name = "PRG",
     .x = 50,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "PRG",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "H",
     .left = "I/O",
     .is_menu = 1,
     .right = 0,
     .sub = 0     },
    {.name = "CST",
     .x = 100,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "CST",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "I",
     .left = "MODES",
     .is_menu = 1,
     .right = 0,
     .sub = 0     },
    {.name = "VAR",
     .x = 150,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "VAR",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "J",
     .left = "MEMORY",
     .is_menu = 1,
     .right = 0,
     .sub = 0     },
    {.name = "UP",
     .x = 200,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = up_width,
     .lh = up_height,
     .lb = up_bitmap,
     .letter = "K",
     .left = "LIBRARY",
     .is_menu = 1,
     .right = 0,
     .sub = 0     },
    {.name = "NXT",
     .x = 250,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "NXT",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "L",
     .left = "PREV",
     .is_menu = 0,
     .right = 0,
     .sub = 0     },

    {.name = "COLON",
     .x = 0,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = colon_width,
     .lh = colon_height,
     .lb = colon_bitmap,
     .letter = "M",
     .left = "UP",
     .is_menu = 0,
     .right = "HOME",
     .sub = 0     },
    {.name = "STO",
     .x = 50,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "STO",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "N",
     .left = "DEF",
     .is_menu = 0,
     .right = "RCL",
     .sub = 0     },
    {.name = "EVAL",
     .x = 100,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "EVAL",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "O",
     .left = "aQ",
     .is_menu = 0,
     .right = "aNUM",
     .sub = 0     },
    {.name = "LEFT",
     .x = 150,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = left_width,
     .lh = left_height,
     .lb = left_bitmap,
     .letter = "P",
     .left = "GRAPH",
     .is_menu = 0,
     .right = 0,
     .sub = 0     },
    {.name = "DOWN",
     .x = 200,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = down_width,
     .lh = down_height,
     .lb = down_bitmap,
     .letter = "Q",
     .left = "REVIEW",
     .is_menu = 0,
     .right = 0,
     .sub = 0     },
    {.name = "RIGHT",
     .x = 250,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = right_width,
     .lh = right_height,
     .lb = right_bitmap,
     .letter = "R",
     .left = "SWAP",
     .is_menu = 0,
     .right = 0,
     .sub = 0     },

    {.name = "SIN",
     .x = 0,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "SIN",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "S",
     .left = "ASIN",
     .is_menu = 0,
     .right = "b",
     .sub = 0     },
    {.name = "COS",
     .x = 50,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "COS",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "T",
     .left = "ACOS",
     .is_menu = 0,
     .right = "c",
     .sub = 0     },
    {.name = "TAN",
     .x = 100,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "TAN",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "U",
     .left = "ATAN",
     .is_menu = 0,
     .right = "d",
     .sub = 0     },
    {.name = "SQRT",
     .x = 150,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = sqrt_width,
     .lh = sqrt_height,
     .lb = sqrt_bitmap,
     .letter = "V",
     .left = "e",
     .is_menu = 0,
     .right = "f",
     .sub = 0     },
    {.name = "POWER",
     .x = 200,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = power_width,
     .lh = power_height,
     .lb = power_bitmap,
     .letter = "W",
     .left = "g",
     .is_menu = 0,
     .right = "LOG",
     .sub = 0     },
    {.name = "INV",
     .x = 250,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = inv_width,
     .lh = inv_height,
     .lb = inv_bitmap,
     .letter = "X",
     .left = "h",
     .is_menu = 0,
     .right = "LN",
     .sub = 0     },

    {.name = "ENTER",
     .x = 0,
     .y = 200,
     .w = 86,
     .h = 26,
     .lc = WHITE,
     .label = "ENTER",
     .font_size = 2,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "EQUATION",
     .is_menu = 0,
     .right = "MATRIX",
     .sub = 0     },
    {.name = "NEG",
     .x = 100,
     .y = 200,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = neg_width,
     .lh = neg_height,
     .lb = neg_bitmap,
     .letter = "Y",
     .left = "EDIT",
     .is_menu = 0,
     .right = "VISIT",
     .sub = 0     },
    {.name = "EEX",
     .x = 150,
     .y = 200,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "EEX",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "Z",
     .left = "2D",
     .is_menu = 0,
     .right = "3D",
     .sub = 0     },
    {.name = "DEL",
     .x = 200,
     .y = 200,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "DEL",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "PURGE",
     .is_menu = 0,
     .right = 0,
     .sub = 0     },
    {.name = "BS",
     .x = 250,
     .y = 200,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = bs_width,
     .lh = bs_height,
     .lb = bs_bitmap,
     .letter = 0,
     .left = "DROP",
     .is_menu = 0,
     .right = "CLR",
     .sub = 0     },

    {.name = "ALPHA",
     .x = 0,
     .y = 250,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = alpha_width,
     .lh = alpha_height,
     .lb = alpha_bitmap,
     .letter = 0,
     .left = "USR",
     .is_menu = 0,
     .right = "ENTRY",
     .sub = 0     },
    {.name = "7",
     .x = 60,
     .y = 250,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "7",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "SOLVE",
     .is_menu = 1,
     .right = 0,
     .sub = 0     },
    {.name = "8",
     .x = 120,
     .y = 250,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "8",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "PLOT",
     .is_menu = 1,
     .right = 0,
     .sub = 0     },
    {.name = "9",
     .x = 180,
     .y = 250,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "9",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "ALGEBRA",
     .is_menu = 1,
     .right = 0,
     .sub = 0     },
    {.name = "DIV",
     .x = 240,
     .y = 250,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = div_width,
     .lh = div_height,
     .lb = div_bitmap,
     .letter = 0,
     .left = "( )",
     .is_menu = 0,
     .right = "#",
     .sub = 0     },

    {.name = "SHL",
     .x = 0,
     .y = 300,
     .w = 36,
     .h = 26,
     .lc = LEFT,
     .label = 0,
     .font_size = 0,
     .lw = shl_width,
     .lh = shl_height,
     .lb = shl_bitmap,
     .letter = 0,
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0     },
    {.name = "4",
     .x = 60,
     .y = 300,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "4",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "TIME",
     .is_menu = 1,
     .right = 0,
     .sub = 0     },
    {.name = "5",
     .x = 120,
     .y = 300,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "5",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "STAT",
     .is_menu = 1,
     .right = 0,
     .sub = 0     },
    {.name = "6",
     .x = 180,
     .y = 300,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "6",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "UNITS",
     .is_menu = 1,
     .right = 0,
     .sub = 0     },
    {.name = "MUL",
     .x = 240,
     .y = 300,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = mul_width,
     .lh = mul_height,
     .lb = mul_bitmap,
     .letter = 0,
     .left = "[ ]",
     .is_menu = 0,
     .right = "_",
     .sub = 0     },

    {.name = "SHR",
     .x = 0,
     .y = 350,
     .w = 36,
     .h = 26,
     .lc = RIGHT,
     .label = 0,
     .font_size = 0,
     .lw = shr_width,
     .lh = shr_height,
     .lb = shr_bitmap,
     .letter = 0,
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0     },
    {.name = "1",
     .x = 60,
     .y = 350,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "1",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "RAD",
     .is_menu = 0,
     .right = "POLAR",
     .sub = 0     },
    {.name = "2",
     .x = 120,
     .y = 350,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "2",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "STACK",
     .is_menu = 0,
     .right = "ARG",
     .sub = 0     },
    {.name = "3",
     .x = 180,
     .y = 350,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "3",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "CMD",
     .is_menu = 0,
     .right = "MENU",
     .sub = 0     },
    {.name = "MINUS",
     .x = 240,
     .y = 350,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = minus_width,
     .lh = minus_height,
     .lb = minus_bitmap,
     .letter = 0,
     .left = "i",
     .is_menu = 0,
     .right = "j",
     .sub = 0     },

    {.name = "ON",
     .x = 0,
     .y = 400,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "ON",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "CONT",
     .is_menu = 0,
     .right = "OFF",
     .sub = "ATTN"},
    {.name = "0",
     .x = 60,
     .y = 400,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "0",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "= ",
     .is_menu = 0,
     .right = " a",
     .sub = 0     },
    {.name = "PERIOD",
     .x = 120,
     .y = 400,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = ".",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = ",",
     .is_menu = 0,
     .right = " k",
     .sub = 0     },
    {.name = "SPC",
     .x = 180,
     .y = 400,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "SPC",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "l ",
     .is_menu = 0,
     .right = " m",
     .sub = 0     },
    {.name = "PLUS",
     .x = 240,
     .y = 400,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = plus_width,
     .lh = plus_height,
     .lb = plus_bitmap,
     .letter = 0,
     .left = "{ }",
     .is_menu = 0,
     .right = ": :",
     .sub = 0     },
};

button_t buttons_gx[ NB_KEYS ] = {
    {.name = "A",
     .x = 0,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "A",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0       },
    {.name = "B",
     .x = 50,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "B",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0       },
    {.name = "C",
     .x = 100,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "C",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0       },
    {.name = "D",
     .x = 150,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "D",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0       },
    {.name = "E",
     .x = 200,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "E",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0       },
    {.name = "F",
     .x = 250,
     .y = 0,
     .w = 36,
     .h = 23,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = menu_label_width,
     .lh = menu_label_height,
     .lb = menu_label_bitmap,
     .letter = "F",
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0       },

    {.name = "MTH",
     .x = 0,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "MTH",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "G",
     .left = "RAD",
     .is_menu = 0,
     .right = "POLAR",
     .sub = 0       },
    {.name = "PRG",
     .x = 50,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "PRG",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "H",
     .left = 0,
     .is_menu = 0,
     .right = "CHARS",
     .sub = 0       },
    {.name = "CST",
     .x = 100,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "CST",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "I",
     .left = 0,
     .is_menu = 0,
     .right = "MODES",
     .sub = 0       },
    {.name = "VAR",
     .x = 150,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "VAR",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "J",
     .left = 0,
     .is_menu = 0,
     .right = "MEMORY",
     .sub = 0       },
    {.name = "UP",
     .x = 200,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = up_width,
     .lh = up_height,
     .lb = up_bitmap,
     .letter = "K",
     .left = 0,
     .is_menu = 0,
     .right = "STACK",
     .sub = 0       },
    {.name = "NXT",
     .x = 250,
     .y = 50,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "NXT",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "L",
     .left = "PREV",
     .is_menu = 0,
     .right = "MENU",
     .sub = 0       },

    {.name = "COLON",
     .x = 0,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = colon_width,
     .lh = colon_height,
     .lb = colon_bitmap,
     .letter = "M",
     .left = "UP",
     .is_menu = 0,
     .right = "HOME",
     .sub = 0       },
    {.name = "STO",
     .x = 50,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "STO",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "N",
     .left = "DEF",
     .is_menu = 0,
     .right = "RCL",
     .sub = 0       },
    {.name = "EVAL",
     .x = 100,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "EVAL",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "O",
     .left = "aNUM",
     .is_menu = 0,
     .right = "UNDO",
     .sub = 0       },
    {.name = "LEFT",
     .x = 150,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = left_width,
     .lh = left_height,
     .lb = left_bitmap,
     .letter = "P",
     .left = "PICTURE",
     .is_menu = 0,
     .right = 0,
     .sub = 0       },
    {.name = "DOWN",
     .x = 200,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = down_width,
     .lh = down_height,
     .lb = down_bitmap,
     .letter = "Q",
     .left = "VIEW",
     .is_menu = 0,
     .right = 0,
     .sub = 0       },
    {.name = "RIGHT",
     .x = 250,
     .y = 100,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = right_width,
     .lh = right_height,
     .lb = right_bitmap,
     .letter = "R",
     .left = "SWAP",
     .is_menu = 0,
     .right = 0,
     .sub = 0       },

    {.name = "SIN",
     .x = 0,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "SIN",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "S",
     .left = "ASIN",
     .is_menu = 0,
     .right = "b",
     .sub = 0       },
    {.name = "COS",
     .x = 50,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "COS",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "T",
     .left = "ACOS",
     .is_menu = 0,
     .right = "c",
     .sub = 0       },
    {.name = "TAN",
     .x = 100,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "TAN",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "U",
     .left = "ATAN",
     .is_menu = 0,
     .right = "d",
     .sub = 0       },
    {.name = "SQRT",
     .x = 150,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = sqrt_width,
     .lh = sqrt_height,
     .lb = sqrt_bitmap,
     .letter = "V",
     .left = "n",
     .is_menu = 0,
     .right = "o",
     .sub = 0       },
    {.name = "POWER",
     .x = 200,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = power_width,
     .lh = power_height,
     .lb = power_bitmap,
     .letter = "W",
     .left = "p",
     .is_menu = 0,
     .right = "LOG",
     .sub = 0       },
    {.name = "INV",
     .x = 250,
     .y = 150,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = inv_width,
     .lh = inv_height,
     .lb = inv_bitmap,
     .letter = "X",
     .left = "q",
     .is_menu = 0,
     .right = "LN",
     .sub = 0       },

    {.name = "ENTER",
     .x = 0,
     .y = 200,
     .w = 86,
     .h = 26,
     .lc = WHITE,
     .label = "ENTER",
     .font_size = 2,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "EQUATION",
     .is_menu = 0,
     .right = "MATRIX",
     .sub = 0       },
    {.name = "NEG",
     .x = 100,
     .y = 200,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = neg_width,
     .lh = neg_height,
     .lb = neg_bitmap,
     .letter = "Y",
     .left = "EDIT",
     .is_menu = 0,
     .right = "CMD",
     .sub = 0       },
    {.name = "EEX",
     .x = 150,
     .y = 200,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "EEX",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = "Z",
     .left = "PURG",
     .is_menu = 0,
     .right = "ARG",
     .sub = 0       },
    {.name = "DEL",
     .x = 200,
     .y = 200,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "DEL",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "CLEAR",
     .is_menu = 0,
     .right = 0,
     .sub = 0       },
    {.name = "BS",
     .x = 250,
     .y = 200,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = bs_width,
     .lh = bs_height,
     .lb = bs_bitmap,
     .letter = 0,
     .left = "DROP",
     .is_menu = 0,
     .right = 0,
     .sub = 0       },

    {.name = "ALPHA",
     .x = 0,
     .y = 250,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = alpha_width,
     .lh = alpha_height,
     .lb = alpha_bitmap,
     .letter = 0,
     .left = "USER",
     .is_menu = 0,
     .right = "ENTRY",
     .sub = 0       },
    {.name = "7",
     .x = 60,
     .y = 250,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "7",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "SOLVE",
     .is_menu = 1,
     .right = 0,
     .sub = 0       },
    {.name = "8",
     .x = 120,
     .y = 250,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "8",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "PLOT",
     .is_menu = 1,
     .right = 0,
     .sub = 0       },
    {.name = "9",
     .x = 180,
     .y = 250,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "9",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "SYMBOLIC",
     .is_menu = 1,
     .right = 0,
     .sub = 0       },
    {.name = "DIV",
     .x = 240,
     .y = 250,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = div_width,
     .lh = div_height,
     .lb = div_bitmap,
     .letter = 0,
     .left = "r ",
     .is_menu = 0,
     .right = "s",
     .sub = 0       },

    {.name = "SHL",
     .x = 0,
     .y = 300,
     .w = 36,
     .h = 26,
     .lc = LEFT,
     .label = 0,
     .font_size = 0,
     .lw = shl_width,
     .lh = shl_height,
     .lb = shl_bitmap,
     .letter = 0,
     .left = 0,
     .is_menu = 0,
     .right = 0,
     .sub = 0       },
    {.name = "4",
     .x = 60,
     .y = 300,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "4",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "TIME",
     .is_menu = 1,
     .right = 0,
     .sub = 0       },
    {.name = "5",
     .x = 120,
     .y = 300,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "5",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "STAT",
     .is_menu = 1,
     .right = 0,
     .sub = 0       },
    {.name = "6",
     .x = 180,
     .y = 300,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "6",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "UNITS",
     .is_menu = 1,
     .right = 0,
     .sub = 0       },
    {.name = "MUL",
     .x = 240,
     .y = 300,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = mul_width,
     .lh = mul_height,
     .lb = mul_bitmap,
     .letter = 0,
     .left = "t ",
     .is_menu = 0,
     .right = "u",
     .sub = 0       },

    {.name = "SHR",
     .x = 0,
     .y = 350,
     .w = 36,
     .h = 26,
     .lc = RIGHT,
     .label = 0,
     .font_size = 0,
     .lw = shr_width,
     .lh = shr_height,
     .lb = shr_bitmap,
     .letter = 0,
     .left = " ",
     .is_menu = 1,
     .right = 0,
     .sub = 0       },
    {.name = "1",
     .x = 60,
     .y = 350,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "1",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "I/O",
     .is_menu = 1,
     .right = 0,
     .sub = 0       },
    {.name = "2",
     .x = 120,
     .y = 350,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "2",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "LIBRARY",
     .is_menu = 1,
     .right = 0,
     .sub = 0       },
    {.name = "3",
     .x = 180,
     .y = 350,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "3",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "EQ LIB",
     .is_menu = 1,
     .right = 0,
     .sub = 0       },
    {.name = "MINUS",
     .x = 240,
     .y = 350,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = minus_width,
     .lh = minus_height,
     .lb = minus_bitmap,
     .letter = 0,
     .left = "v ",
     .is_menu = 0,
     .right = "w",
     .sub = 0       },

    {.name = "ON",
     .x = 0,
     .y = 400,
     .w = 36,
     .h = 26,
     .lc = WHITE,
     .label = "ON",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "CONT",
     .is_menu = 0,
     .right = "OFF",
     .sub = "CANCEL"},
    {.name = "0",
     .x = 60,
     .y = 400,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "0",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "\004 ",
     .is_menu = 0,
     .right = "\003",
     .sub = 0       },
    {.name = "PERIOD",
     .x = 120,
     .y = 400,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = ".",
     .font_size = 1,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "\002 ",
     .is_menu = 0,
     .right = "\001",
     .sub = 0       },
    {.name = "SPC",
     .x = 180,
     .y = 400,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = "SPC",
     .font_size = 0,
     .lw = 0,
     .lh = 0,
     .lb = 0,
     .letter = 0,
     .left = "\005 ",
     .is_menu = 0,
     .right = "z",
     .sub = 0       },
    {.name = "PLUS",
     .x = 240,
     .y = 400,
     .w = 46,
     .h = 26,
     .lc = WHITE,
     .label = 0,
     .font_size = 0,
     .lw = plus_width,
     .lh = plus_height,
     .lb = plus_bitmap,
     .letter = 0,
     .left = "x ",
     .is_menu = 0,
     .right = "y",
     .sub = 0       },
};

ann_struct_t ann_tbl[ NB_ANNUNCIATORS ] = {
    {.x = 16,  .y = 4, .width = ann_left_width,    .height = ann_left_height,    .bits = ann_left_bitmap   },
    {.x = 61,  .y = 4, .width = ann_right_width,   .height = ann_right_height,   .bits = ann_right_bitmap  },
    {.x = 106, .y = 4, .width = ann_alpha_width,   .height = ann_alpha_height,   .bits = ann_alpha_bitmap  },
    {.x = 151, .y = 4, .width = ann_battery_width, .height = ann_battery_height, .bits = ann_battery_bitmap},
    {.x = 196, .y = 4, .width = ann_busy_width,    .height = ann_busy_height,    .bits = ann_busy_bitmap   },
    {.x = 241, .y = 4, .width = ann_io_width,      .height = ann_io_height,      .bits = ann_io_bitmap     },
};

void ( *ui_disp_draw_nibble )( word_20 addr, word_4 val );
void ( *ui_menu_draw_nibble )( word_20 addr, word_4 val );
void ( *ui_get_event )( void );
void ( *ui_update_LCD )( void );
void ( *ui_refresh_LCD )( void );
void ( *ui_adjust_contrast )( void );
void ( *ui_draw_annunc )( void );

void ui_init_LCD( void ) { memset( lcd_nibbles_buffer, 0xf0, sizeof( lcd_nibbles_buffer ) ); }

int SmallTextWidth( const char* string, unsigned int length )
{
    int w = 0;
    for ( unsigned int i = 0; i < length; i++ ) {
        if ( small_font[ ( int )string[ i ] ].h != 0 )
            w += small_font[ ( int )string[ i ] ].w + 1;
        else {
            if ( config.verbose )
                fprintf( stderr, "Unknown small letter 0x00%x\n", ( int )string[ i ] );
            w += 5;
        }
    }

    return w;
}

void start_UI( int argc, char** argv )
{
    ui_init_LCD();

    switch ( config.frontend_type ) {
#if defined( HAS_X11 )
        case FRONTEND_X11:
        default:
            init_x11_ui( argc, argv );
            break;
#endif

#if defined( HAS_SDL2 )
        case FRONTEND_SDL2:
#  if !defined( HAS_X11 )
        default:
#  endif
            init_sdl2_ui( argc, argv );
            break;
#endif

#if defined( HAS_SDL )
        case FRONTEND_SDL:
#  if !defined( HAS_X11 )
        default:
#  endif
            init_sdl_ui( argc, argv );
            break;
#endif

        case FRONTEND_TEXT:
#if ( !defined( HAS_X11 ) && !defined( HAS_SDL2 ) && !defined( HAS_SDL ) )
        default:
#endif
            init_text_ui( argc, argv );
            break;
    }
}

void ui_stop( void )
{
    switch ( config.frontend_type ) {
#if defined( HAS_X11 )
        case FRONTEND_X11:
        default:
            x11_ui_stop();
            break;
#endif

#if defined( HAS_SDL2 )
        case FRONTEND_SDL2:
#  if !defined( HAS_X11 )
        default:
#  endif
            sdl2_ui_stop();
            break;
#endif

#if defined( HAS_SDL )
        case FRONTEND_SDL:
#  if !defined( HAS_X11 )
        default:
#  endif
            sdl_ui_stop();
            break;
#endif

        case FRONTEND_TEXT:
#if ( !defined( HAS_X11 ) && !defined( HAS_SDL2 ) && !defined( HAS_SDL ) )
        default:
#endif
            text_ui_stop();
            break;
    }
}

void close_and_exit( void )
{
    ui_stop();
    exit_emulator();

    exit( 0 );
}
